import { ReactNode } from 'react';
import {
  View,
    Text,
      TouchableOpacity,
        StyleSheet,
          ScrollView,
          } from 'react-native';
          import { SafeAreaView } from 'react-native-safe-area-context';
          import { ChevronLeft } from 'lucide-react-native';

          interface Props {
            step: number;
              totalSteps: number;
                title: string;
                  subtitle?: string;
                    onBack?: () => void;
                      children: ReactNode;
                        /** If provided, renders a primary CTA button at the bottom */
                          ctaLabel?: string;
                            onCta?: () => void;
                              ctaDisabled?: boolean;
                                /** Optional secondary/skip label */
                                  skipLabel?: string;
                                    onSkip?: () => void;
                                    }

                                    export default function StepBase({
                                      step,
                                        totalSteps,
                                          title,
                                            subtitle,
                                              onBack,
                                                children,
                                                  ctaLabel,
                                                    onCta,
                                                      ctaDisabled,
                                                        skipLabel,
                                                          onSkip,
                                                          }: Props) {
                                                            const progress = ((step + 1) / totalSteps) * 100;

                                                              return (
                                                                  <SafeAreaView style={s.safe}>
                                                                        {/* Progress bar */}
                                                                              <View style={s.progressTrack}>
                                                                                      <View style={[s.progressFill, { width: `${progress}%` as any }]} />
                                                                                            </View>

                                                                                                  {/* Header row */}
                                                                                                        <View style={s.headerRow}>
                                                                                                                {onBack && step > 0 ? (
                                                                                                                          <TouchableOpacity onPress={onBack} style={s.backBtn}>
                                                                                                                                      <ChevronLeft color="#6b7280" size={22} />
                                                                                                                                                </TouchableOpacity>
                                                                                                                                                        ) : (
                                                                                                                                                                  <View style={s.backBtn} />
                                                                                                                                                                          )}
                                                                                                                                                                                  <Text style={s.stepCount}>{step + 1} of {totalSteps}</Text>
                                                                                                                                                                                          {skipLabel && onSkip ? (
                                                                                                                                                                                                    <TouchableOpacity onPress={onSkip} style={s.skipBtn}>
                                                                                                                                                                                                                <Text style={s.skipTxt}>{skipLabel}</Text>
                                                                                                                                                                                                                          </TouchableOpacity>
                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                            <View style={s.skipBtn} />
                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                          </View>

                                                                                                                                                                                                                                                                <ScrollView
                                                                                                                                                                                                                                                                        style={s.scroll}
                                                                                                                                                                                                                                                                                contentContainerStyle={s.scrollContent}
                                                                                                                                                                                                                                                                                        keyboardShouldPersistTaps="handled"
                                                                                                                                                                                                                                                                                                showsVerticalScrollIndicator={false}
                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                              <Text style={s.title}>{title}</Text>
                                                                                                                                                                                                                                                                                                                      {subtitle ? <Text style={s.subtitle}>{subtitle}</Text> : null}
                                                                                                                                                                                                                                                                                                                              <View style={s.body}>{children}</View>
                                                                                                                                                                                                                                                                                                                                    </ScrollView>

                                                                                                                                                                                                                                                                                                                                          {/* CTA button */}
                                                                                                                                                                                                                                                                                                                                                {ctaLabel && onCta && (
                                                                                                                                                                                                                                                                                                                                                        <View style={s.footer}>
                                                                                                                                                                                                                                                                                                                                                                  <TouchableOpacity
                                                                                                                                                                                                                                                                                                                                                                              style={[s.cta, ctaDisabled && s.ctaOff]}
                                                                                                                                                                                                                                                                                                                                                                                          onPress={onCta}
                                                                                                                                                                                                                                                                                                                                                                                                      disabled={ctaDisabled}
                                                                                                                                                                                                                                                                                                                                                                                                                  activeOpacity={0.85}
                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                        <Text style={s.ctaTxt}>{ctaLabel}</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </TouchableOpacity>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </SafeAreaView>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const s = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        safe: { flex: 1, backgroundColor: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          progressTrack: { height: 3, backgroundColor: '#f3f4f6' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            progressFill: { height: 3, backgroundColor: '#9333ea' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              headerRow: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  flexDirection: 'row',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          justifyContent: 'space-between',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              paddingHorizontal: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  paddingTop: 12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      paddingBottom: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          backBtn: { width: 36, height: 36, justifyContent: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            stepCount: { fontSize: 12, color: '#9ca3af', fontWeight: '500' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              skipBtn: { width: 60, alignItems: 'flex-end', justifyContent: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                skipTxt: { fontSize: 14, color: '#9333ea', fontWeight: '500' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  scroll: { flex: 1 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scrollContent: { paddingHorizontal: 24, paddingTop: 24, paddingBottom: 32 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      title: { fontSize: 28, fontWeight: '800', color: '#111827', lineHeight: 34, marginBottom: 8 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        subtitle: { fontSize: 16, color: '#6b7280', lineHeight: 22, marginBottom: 28 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          body: { gap: 12 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            footer: { paddingHorizontal: 24, paddingBottom: 16, paddingTop: 8, backgroundColor: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              cta: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backgroundColor: '#9333ea',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      borderRadius: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          paddingVertical: 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              alignItems: 'center',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  shadowColor: '#9333ea',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      shadowOpacity: 0.3,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          shadowRadius: 8,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              elevation: 4,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ctaOff: { backgroundColor: '#e9d5ff', shadowOpacity: 0 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ctaTxt: { fontSize: 17, fontWeight: '700', color: '#fff' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });