export const metadata = {
  title: "Terms of Service — BioPrecision",
  description: "Terms of Service for the BioPrecision health intelligence platform.",
};

export default function TermsOfService() {
  const updated = "May 18, 2026";

  return (
    <div style={{ maxWidth: 720, margin: "0 auto", padding: "48px 24px", fontFamily: "system-ui, sans-serif", color: "#1f2937", lineHeight: 1.7 }}>
      <div style={{ marginBottom: 40 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 8 }}>
          <div style={{ width: 36, height: 36, borderRadius: 10, background: "#C96A2B", display: "flex", alignItems: "center", justifyContent: "center" }}>
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.5" strokeLinecap="round">
              <path d="M2 12h3l3-8 3 16 3-10 3 5 2-3h3" />
            </svg>
          </div>
          <span style={{ fontWeight: 700, fontSize: 18, color: "#111827" }}>BioPrecision</span>
        </div>
        <h1 style={{ fontSize: 32, fontWeight: 800, color: "#111827", margin: "0 0 8px" }}>Terms of Service</h1>
        <p style={{ color: "#6b7280", fontSize: 14, margin: 0 }}>Last updated: {updated}</p>
      </div>

      <Section title="Acceptance of Terms">
        By downloading, installing, or using the BioPrecision application ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.
      </Section>

      <Section title="Description of Service">
        BioPrecision is a health intelligence platform that converts laboratory biomarker results and lifestyle data into personalised daily health actions and AI-powered coaching. The App is intended for informational and educational purposes only.
      </Section>

      <Section title="Not Medical Advice">
        <p><strong>BioPrecision is not a medical device. The App does not provide medical diagnoses, prescriptions, treatment plans, or clinical medical advice.</strong></p>
        <p>All content generated by the App — including AI coach responses, biomarker interpretations, and daily action recommendations — is for informational and educational purposes only. Always consult a qualified healthcare provider before making changes to your health regimen, medications, supplements, or lifestyle.</p>
        <p>In the event of a medical emergency, call emergency services immediately. Do not rely on the App for emergency health guidance.</p>
      </Section>

      <Section title="Eligibility">
        You must be at least 18 years of age to use the App. By using the App, you represent that you meet this requirement. The App is not intended for use by minors.
      </Section>

      <Section title="Your Account and Data">
        <p>You are responsible for maintaining the confidentiality of your account credentials. You are responsible for all activity that occurs under your account.</p>
        <p>You retain ownership of all health data you provide to the App. By using the App, you grant BioPrecision a limited license to process your health data solely for the purpose of providing the service as described in our Privacy Policy.</p>
        <p>You may request deletion of your account and all associated data at any time by contacting us at privacy@bioprecision.org. Deletion requests are processed within 30 days.</p>
      </Section>

      <Section title="Acceptable Use">
        You agree not to:
        <ul style={{ paddingLeft: 20, margin: "8px 0" }}>
          <li>Use the App for any unlawful purpose</li>
          <li>Attempt to reverse engineer, decompile, or extract the App's source code</li>
          <li>Use the App to store or transmit malicious code</li>
          <li>Attempt to gain unauthorised access to any systems or data</li>
          <li>Resell or redistribute the App or its content without written permission</li>
          <li>Use the App in any way that could harm, disable, or impair our systems</li>
        </ul>
      </Section>

      <Section title="AI-Generated Content">
        The App uses Anthropic's Claude AI to generate health coaching responses and recommendations. AI-generated content may contain errors or omissions. BioPrecision does not guarantee the accuracy, completeness, or appropriateness of AI-generated content for your specific health situation. You should independently verify any health information before acting on it.
      </Section>

      <Section title="Wearable Device Integrations">
        The App may connect to third-party wearable devices and health platforms (such as Oura Ring and WHOOP) via OAuth2. Your use of these integrations is subject to the terms of service of the respective third-party providers. BioPrecision is not responsible for the availability, accuracy, or security of third-party wearable data.
      </Section>

      <Section title="Clinic and Practitioner Use">
        If you access the App through a clinic or healthcare provider, your use may be subject to additional terms established by that organisation. Practitioner access to your data is governed by your clinic's policies and applicable healthcare privacy laws.
      </Section>

      <Section title="Intellectual Property">
        The App, including its design, code, content, and underlying technology, is owned by BioPrecision and is protected by intellectual property laws. Nothing in these Terms grants you any rights to use BioPrecision's trademarks, logos, or brand elements.
      </Section>

      <Section title="Disclaimers and Limitation of Liability">
        <p>THE APP IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED. BIOPRECISION DOES NOT WARRANT THAT THE APP WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT DEFECTS WILL BE CORRECTED.</p>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, BIOPRECISION SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE APP, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF HEALTH OUTCOMES, DATA, OR REVENUE.</p>
        <p>BIOPRECISION'S TOTAL LIABILITY FOR ANY CLAIMS ARISING UNDER THESE TERMS SHALL NOT EXCEED THE AMOUNT YOU PAID FOR THE APP IN THE 12 MONTHS PRECEDING THE CLAIM.</p>
      </Section>

      <Section title="Changes to the App and Terms">
        <p>BioPrecision reserves the right to modify, suspend, or discontinue the App at any time with or without notice. We will provide notice of material changes to these Terms via in-app notification or email.</p>
        <p>Your continued use of the App after changes to these Terms constitutes acceptance of the updated Terms.</p>
      </Section>

      <Section title="Governing Law">
        These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved through binding arbitration in Delaware.
      </Section>

      <Section title="Contact">
        <p>For questions about these Terms:</p>
        <p style={{ margin: 0 }}>
          <strong>BioPrecision</strong><br />
          Email: <a href="mailto:legal@bioprecision.org" style={{ color: "#C96A2B" }}>legal@bioprecision.org</a>
        </p>
      </Section>

      <div style={{ marginTop: 48, paddingTop: 24, borderTop: "1px solid #e5e7eb", color: "#9ca3af", fontSize: 13 }}>
        © {new Date().getFullYear()} BioPrecision. All rights reserved.
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 32 }}>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: "#111827", marginBottom: 12, marginTop: 0 }}>{title}</h2>
      <div style={{ fontSize: 15, color: "#374151" }}>{children}</div>
    </div>
  );
}
